// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package domain

import (
	"context"
	"sync"
)

// Ensure, that ContextBrokerClientMock does implement ContextBrokerClient.
// If this is not the case, regenerate this file with moq.
var _ ContextBrokerClient = &ContextBrokerClientMock{}

// ContextBrokerClientMock is a mock implementation of ContextBrokerClient.
//
// 	func TestSomethingThatUsesContextBrokerClient(t *testing.T) {
//
// 		// make and configure a mocked ContextBrokerClient
// 		mockedContextBrokerClient := &ContextBrokerClientMock{
// 			AddEntityFunc: func(ctx context.Context, entity interface{}) error {
// 				panic("mock out the AddEntity method")
// 			},
// 		}
//
// 		// use mockedContextBrokerClient in code that requires ContextBrokerClient
// 		// and then make assertions.
//
// 	}
type ContextBrokerClientMock struct {
	// AddEntityFunc mocks the AddEntity method.
	AddEntityFunc func(ctx context.Context, entity interface{}) error

	// calls tracks calls to the methods.
	calls struct {
		// AddEntity holds details about calls to the AddEntity method.
		AddEntity []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity interface{}
		}
	}
	lockAddEntity sync.RWMutex
}

// AddEntity calls AddEntityFunc.
func (mock *ContextBrokerClientMock) AddEntity(ctx context.Context, entity interface{}) error {
	if mock.AddEntityFunc == nil {
		panic("ContextBrokerClientMock.AddEntityFunc: method is nil but ContextBrokerClient.AddEntity was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity interface{}
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockAddEntity.Lock()
	mock.calls.AddEntity = append(mock.calls.AddEntity, callInfo)
	mock.lockAddEntity.Unlock()
	return mock.AddEntityFunc(ctx, entity)
}

// AddEntityCalls gets all the calls that were made to AddEntity.
// Check the length with:
//     len(mockedContextBrokerClient.AddEntityCalls())
func (mock *ContextBrokerClientMock) AddEntityCalls() []struct {
	Ctx    context.Context
	Entity interface{}
} {
	var calls []struct {
		Ctx    context.Context
		Entity interface{}
	}
	mock.lockAddEntity.RLock()
	calls = mock.calls.AddEntity
	mock.lockAddEntity.RUnlock()
	return calls
}
